# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nodecap2
tagline:          'ICAP server framework for node.js - create custom HTTP proxy filters for Squid, etc.'
description:      'An ICAP server framework for node.js - create custom HTTP proxy filters for Squid, etc.'
url:              http://horpto.github.io/nodecap2
baseurl:	        /nodecap2

author:
  name:           'Joseph Savona'
  url:            http://josephsavona.com

paginate:         1

# Custom vars
version:          0.1.3

github:
  repo:           https://github.com/horpto/nodecap2
